// Unitless CSS properties as described by Vanilla Extract
//
// https://github.com/vanilla-extract-css/vanilla-extract/blob/6068246343ceb58a04006f4ce9d9ff7ecc7a6c09/packages/css/src/transformCss.ts#L25
export const unitless: Record<string, boolean> = {
	"aspect-ratio":              true, // Added
	"animation-iteration-count": true,
	"border-image":              true,
	"border-image-outset":       true,
	"border-image-slice":        true,
	"border-image-width":        true,
	"box-flex":                  true,
	"box-flex-group":            true,
	"column-count":              true,
	"columns":                   true,
	"flex":                      true,
	"flex-grow":                 true,
	"flex-shrink":               true,
	"font-weight":               true,
	"grid-area":                 true,
	"grid-column":               true,
	"grid-column-end":           true,
	"grid-column-start":         true,
	"grid-row":                  true,
	"grid-row-end":              true,
	"grid-row-start":            true,
	"initial-letter":            true,
	"line-clamp":                true,
	"line-height":               true,
	"max-lines":                 true,
	"opacity":                   true,
	"order":                     true,
	"orphans":                   true,
	"scale":                     true, // Added
	"tab-size":                  true,
	"webkit-line-clamp":         true,
	"widows":                    true,
	"z-index":                   true,
	"zoom":                      true,

	// SVG
	"fill-opacity":              true,
	"flood-opacity":             true,
	"mask-border":               true,
	"mask-border-outset":        true,
	"mask-border-slice":         true,
	"mask-border-width":         true,
	"shape-image-threshold":     true,
	"stop-opacity":              true,
	"stroke-dashoffset":         true,
	"stroke-miterlimit":         true,
	"stroke-opacity":            true,
	"stroke-width":              true,
}
