import * as Hero from "react-heroicons"

// NOTE: The following have been manually exported:
//
// - arrows-expand
// - fire
// - folder-add
// - folder-download
// - folder-remove
// - shopping-bag
//
// https://github.com/refactoringui/heroicons/issues/55
const originalIcons = [
	{
		tags: ["adjustments"],
		name: "adjustments",
		outline: Hero.AdjustmentsOutlineMd,
		solid: Hero.AdjustmentsSolidSm,
		statusNew: false,
	},
	{
		tags: ["annotation"],
		name: "annotation",
		outline: Hero.AnnotationOutlineMd,
		solid: Hero.AnnotationSolidSm,
		statusNew: false,
	},
	{
		tags: ["archive"],
		name: "archive",
		outline: Hero.ArchiveOutlineMd,
		solid: Hero.ArchiveSolidSm,
		statusNew: false,
	},
	{
		tags: ["arrow-circle-down", "arrow", "circle", "down"],
		name: "arrow-circle-down",
		outline: Hero.ArrowCircleDownOutlineMd,
		solid: Hero.ArrowCircleDownSolidSm,
		statusNew: false,
	},
	{
		tags: ["arrow-circle-left", "arrow", "circle", "left"],
		name: "arrow-circle-left",
		outline: Hero.ArrowCircleLeftOutlineMd,
		solid: Hero.ArrowCircleLeftSolidSm,
		statusNew: false,
	},
	{
		tags: ["arrow-circle-right", "arrow", "circle", "right"],
		name: "arrow-circle-right",
		outline: Hero.ArrowCircleRightOutlineMd,
		solid: Hero.ArrowCircleRightSolidSm,
		statusNew: false,
	},
	{
		tags: ["arrow-circle-up", "arrow", "circle", "up"],
		name: "arrow-circle-up",
		outline: Hero.ArrowCircleUpOutlineMd,
		solid: Hero.ArrowCircleUpSolidSm,
		statusNew: false,
	},
	{
		tags: ["arrow-down", "arrow", "down"],
		name: "arrow-down",
		outline: Hero.ArrowDownOutlineMd,
		solid: Hero.ArrowDownSolidSm,
		statusNew: false,
	},
	{
		tags: ["arrow-left", "arrow", "left"],
		name: "arrow-left",
		outline: Hero.ArrowLeftOutlineMd,
		solid: Hero.ArrowLeftSolidSm,
		statusNew: false,
	},
	{
		tags: ["arrow-narrow-down", "arrow", "narrow", "down"],
		name: "arrow-narrow-down",
		outline: Hero.ArrowNarrowDownOutlineMd,
		solid: Hero.ArrowNarrowDownSolidSm,
		statusNew: false,
	},
	{
		tags: ["arrow-narrow-left", "arrow", "narrow", "left"],
		name: "arrow-narrow-left",
		outline: Hero.ArrowNarrowLeftOutlineMd,
		solid: Hero.ArrowNarrowLeftSolidSm,
		statusNew: false,
	},
	{
		tags: ["arrow-narrow-right", "arrow", "narrow", "right"],
		name: "arrow-narrow-right",
		outline: Hero.ArrowNarrowRightOutlineMd,
		solid: Hero.ArrowNarrowRightSolidSm,
		statusNew: false,
	},
	{
		tags: ["arrow-narrow-up", "arrow", "narrow", "up"],
		name: "arrow-narrow-up",
		outline: Hero.ArrowNarrowUpOutlineMd,
		solid: Hero.ArrowNarrowUpSolidSm,
		statusNew: false,
	},
	{
		tags: ["arrow-right", "arrow", "right"],
		name: "arrow-right",
		outline: Hero.ArrowRightOutlineMd,
		solid: Hero.ArrowRightSolidSm,
		statusNew: false,
	},
	{
		tags: ["arrow-up", "arrow", "up"],
		name: "arrow-up",
		outline: Hero.ArrowUpOutlineMd,
		solid: Hero.ArrowUpSolidSm,
		statusNew: false,
	},
	{
		tags: ["arrows-expand", "arrows", "expand"],
		name: "arrows-expand",
		outline: Hero.ArrowsExpandOutlineMd,
		solid: Hero.ArrowsExpandSolidSm,
		statusNew: true,
	},
	{
		tags: ["at-symbol", "at", "symbol"],
		name: "at-symbol",
		outline: Hero.AtSymbolOutlineMd,
		solid: Hero.AtSymbolSolidSm,
		statusNew: false,
	},
	{
		tags: ["badge-check", "badge", "check"],
		name: "badge-check",
		outline: Hero.BadgeCheckOutlineMd,
		solid: Hero.BadgeCheckSolidSm,
		statusNew: false,
	},
	{
		tags: ["ban"],
		name: "ban",
		outline: Hero.BanOutlineMd,
		solid: Hero.BanSolidSm,
		statusNew: false,
	},
	{
		tags: ["bell"],
		name: "bell",
		outline: Hero.BellOutlineMd,
		solid: Hero.BellSolidSm,
		statusNew: false,
	},
	{
		tags: ["book-open", "book", "open"],
		name: "book-open",
		outline: Hero.BookOpenOutlineMd,
		solid: Hero.BookOpenSolidSm,
		statusNew: false,
	},
	{
		tags: ["bookmark-alt", "bookmark", "alt"],
		name: "bookmark-alt",
		outline: Hero.BookmarkAltOutlineMd,
		solid: Hero.BookmarkAltSolidSm,
		statusNew: false,
	},
	{
		tags: ["bookmark"],
		name: "bookmark",
		outline: Hero.BookmarkOutlineMd,
		solid: Hero.BookmarkSolidSm,
		statusNew: false,
	},
	{
		tags: ["briefcase"],
		name: "briefcase",
		outline: Hero.BriefcaseOutlineMd,
		solid: Hero.BriefcaseSolidSm,
		statusNew: false,
	},
	{
		tags: ["calendar"],
		name: "calendar",
		outline: Hero.CalendarOutlineMd,
		solid: Hero.CalendarSolidSm,
		statusNew: false,
	},
	{
		tags: ["camera"],
		name: "camera",
		outline: Hero.CameraOutlineMd,
		solid: Hero.CameraSolidSm,
		statusNew: false,
	},
	{
		tags: ["cash"],
		name: "cash",
		outline: Hero.CashOutlineMd,
		solid: Hero.CashSolidSm,
		statusNew: false,
	},
	{
		tags: ["chart-bar", "chart", "bar"],
		name: "chart-bar",
		outline: Hero.ChartBarOutlineMd,
		solid: Hero.ChartBarSolidSm,
		statusNew: false,
	},
	{
		tags: ["chart-pie", "chart", "pie"],
		name: "chart-pie",
		outline: Hero.ChartPieOutlineMd,
		solid: Hero.ChartPieSolidSm,
		statusNew: false,
	},
	{
		tags: ["chart-square-bar", "chart", "square", "bar"],
		name: "chart-square-bar",
		outline: Hero.ChartSquareBarOutlineMd,
		solid: Hero.ChartSquareBarSolidSm,
		statusNew: false,
	},
	{
		tags: ["chat-alt2", "chat", "alt2"],
		name: "chat-alt2",
		outline: Hero.ChatAlt2OutlineMd,
		solid: Hero.ChatAlt2SolidSm,
		statusNew: false,
	},
	{
		tags: ["chat-alt", "chat", "alt"],
		name: "chat-alt",
		outline: Hero.ChatAltOutlineMd,
		solid: Hero.ChatAltSolidSm,
		statusNew: false,
	},
	{
		tags: ["chat"],
		name: "chat",
		outline: Hero.ChatOutlineMd,
		solid: Hero.ChatSolidSm,
		statusNew: false,
	},
	{
		tags: ["check-circle", "check", "circle"],
		name: "check-circle",
		outline: Hero.CheckCircleOutlineMd,
		solid: Hero.CheckCircleSolidSm,
		statusNew: false,
	},
	{
		tags: ["check"],
		name: "check",
		outline: Hero.CheckOutlineMd,
		solid: Hero.CheckSolidSm,
		statusNew: false,
	},
	{
		tags: ["chevron-down", "chevron", "down"],
		name: "chevron-down",
		outline: Hero.ChevronDownOutlineMd,
		solid: Hero.ChevronDownSolidSm,
		statusNew: false,
	},
	{
		tags: ["chevron-left", "chevron", "left"],
		name: "chevron-left",
		outline: Hero.ChevronLeftOutlineMd,
		solid: Hero.ChevronLeftSolidSm,
		statusNew: false,
	},
	{
		tags: ["chevron-right", "chevron", "right"],
		name: "chevron-right",
		outline: Hero.ChevronRightOutlineMd,
		solid: Hero.ChevronRightSolidSm,
		statusNew: false,
	},
	{
		tags: ["chevron-up", "chevron", "up"],
		name: "chevron-up",
		outline: Hero.ChevronUpOutlineMd,
		solid: Hero.ChevronUpSolidSm,
		statusNew: false,
	},
	{
		tags: ["clipboard-check", "clipboard", "check"],
		name: "clipboard-check",
		outline: Hero.ClipboardCheckOutlineMd,
		solid: Hero.ClipboardCheckSolidSm,
		statusNew: false,
	},
	{
		tags: ["clipboard-copy", "clipboard", "copy"],
		name: "clipboard-copy",
		outline: Hero.ClipboardCopyOutlineMd,
		solid: Hero.ClipboardCopySolidSm,
		statusNew: false,
	},
	{
		tags: ["clipboard-list", "clipboard", "list"],
		name: "clipboard-list",
		outline: Hero.ClipboardListOutlineMd,
		solid: Hero.ClipboardListSolidSm,
		statusNew: false,
	},
	{
		tags: ["clipboard"],
		name: "clipboard",
		outline: Hero.ClipboardOutlineMd,
		solid: Hero.ClipboardSolidSm,
		statusNew: false,
	},
	{
		tags: ["clock"],
		name: "clock",
		outline: Hero.ClockOutlineMd,
		solid: Hero.ClockSolidSm,
		statusNew: false,
	},
	{
		tags: ["cloud-download", "cloud", "download"],
		name: "cloud-download",
		outline: Hero.CloudDownloadOutlineMd,
		solid: Hero.CloudDownloadSolidSm,
		statusNew: false,
	},
	{
		tags: ["cloud-upload", "cloud", "upload"],
		name: "cloud-upload",
		outline: Hero.CloudUploadOutlineMd,
		solid: Hero.CloudUploadSolidSm,
		statusNew: false,
	},
	{
		tags: ["code"],
		name: "code",
		outline: Hero.CodeOutlineMd,
		solid: Hero.CodeSolidSm,
		statusNew: false,
	},
	{
		tags: ["cog"],
		name: "cog",
		outline: Hero.CogOutlineMd,
		solid: Hero.CogSolidSm,
		statusNew: false,
	},
	{
		tags: ["collection"],
		name: "collection",
		outline: Hero.CollectionOutlineMd,
		solid: Hero.CollectionSolidSm,
		statusNew: false,
	},
	{
		tags: ["color-swatch", "color", "swatch"],
		name: "color-swatch",
		outline: Hero.ColorSwatchOutlineMd,
		solid: Hero.ColorSwatchSolidSm,
		statusNew: false,
	},
	{
		tags: ["credit-card", "credit", "card"],
		name: "credit-card",
		outline: Hero.CreditCardOutlineMd,
		solid: Hero.CreditCardSolidSm,
		statusNew: false,
	},
	{
		tags: ["currency-dollar", "currency", "dollar"],
		name: "currency-dollar",
		outline: Hero.CurrencyDollarOutlineMd,
		solid: Hero.CurrencyDollarSolidSm,
		statusNew: false,
	},
	{
		tags: ["currency-euro", "currency", "euro"],
		name: "currency-euro",
		outline: Hero.CurrencyEuroOutlineMd,
		solid: Hero.CurrencyEuroSolidSm,
		statusNew: false,
	},
	{
		tags: ["currency-pound", "currency", "pound"],
		name: "currency-pound",
		outline: Hero.CurrencyPoundOutlineMd,
		solid: Hero.CurrencyPoundSolidSm,
		statusNew: false,
	},
	{
		tags: ["currency-rupee", "currency", "rupee"],
		name: "currency-rupee",
		outline: Hero.CurrencyRupeeOutlineMd,
		solid: Hero.CurrencyRupeeSolidSm,
		statusNew: false,
	},
	{
		tags: ["currency-yen", "currency", "yen"],
		name: "currency-yen",
		outline: Hero.CurrencyYenOutlineMd,
		solid: Hero.CurrencyYenSolidSm,
		statusNew: false,
	},
	{
		tags: ["cursor-click", "cursor", "click"],
		name: "cursor-click",
		outline: Hero.CursorClickOutlineMd,
		solid: Hero.CursorClickSolidSm,
		statusNew: false,
	},
	{
		tags: ["desktop-computer", "desktop", "computer"],
		name: "desktop-computer",
		outline: Hero.DesktopComputerOutlineMd,
		solid: Hero.DesktopComputerSolidSm,
		statusNew: false,
	},
	{
		tags: ["document-add", "document", "add"],
		name: "document-add",
		outline: Hero.DocumentAddOutlineMd,
		solid: Hero.DocumentAddSolidSm,
		statusNew: false,
	},
	{
		tags: ["document-download", "document", "download"],
		name: "document-download",
		outline: Hero.DocumentDownloadOutlineMd,
		solid: Hero.DocumentDownloadSolidSm,
		statusNew: false,
	},
	{
		tags: ["document-duplicate", "document", "duplicate"],
		name: "document-duplicate",
		outline: Hero.DocumentDuplicateOutlineMd,
		solid: Hero.DocumentDuplicateSolidSm,
		statusNew: false,
	},
	{
		tags: ["document-remove", "document", "remove"],
		name: "document-remove",
		outline: Hero.DocumentRemoveOutlineMd,
		solid: Hero.DocumentRemoveSolidSm,
		statusNew: false,
	},
	{
		tags: ["document-report", "document", "report"],
		name: "document-report",
		outline: Hero.DocumentReportOutlineMd,
		solid: Hero.DocumentReportSolidSm,
		statusNew: false,
	},
	{
		tags: ["document"],
		name: "document",
		outline: Hero.DocumentOutlineMd,
		solid: Hero.DocumentSolidSm,
		statusNew: false,
	},
	{
		tags: ["dots-circle-horizontal", "dots", "circle", "horizontal"],
		name: "dots-circle-horizontal",
		outline: Hero.DotsCircleHorizontalOutlineMd,
		solid: Hero.DotsCircleHorizontalSolidSm,
		statusNew: false,
	},
	{
		tags: ["dots-horizontal", "dots", "horizontal"],
		name: "dots-horizontal",
		outline: Hero.DotsHorizontalOutlineMd,
		solid: Hero.DotsHorizontalSolidSm,
		statusNew: false,
	},
	{
		tags: ["dots-vertical", "dots", "vertical"],
		name: "dots-vertical",
		outline: Hero.DotsVerticalOutlineMd,
		solid: Hero.DotsVerticalSolidSm,
		statusNew: false,
	},
	{
		tags: ["download"],
		name: "download",
		outline: Hero.DownloadOutlineMd,
		solid: Hero.DownloadSolidSm,
		statusNew: false,
	},
	{
		tags: ["duplicate"],
		name: "duplicate",
		outline: Hero.DuplicateOutlineMd,
		solid: Hero.DuplicateSolidSm,
		statusNew: false,
	},
	{
		tags: ["emoji-happy", "emoji", "happy"],
		name: "emoji-happy",
		outline: Hero.EmojiHappyOutlineMd,
		solid: Hero.EmojiHappySolidSm,
		statusNew: false,
	},
	{
		tags: ["emoji-sad", "emoji", "sad"],
		name: "emoji-sad",
		outline: Hero.EmojiSadOutlineMd,
		solid: Hero.EmojiSadSolidSm,
		statusNew: false,
	},
	{
		tags: ["exclamation-circle", "exclamation", "circle"],
		name: "exclamation-circle",
		outline: Hero.ExclamationCircleOutlineMd,
		solid: Hero.ExclamationCircleSolidSm,
		statusNew: false,
	},
	{
		tags: ["exclamation"],
		name: "exclamation",
		outline: Hero.ExclamationOutlineMd,
		solid: Hero.ExclamationSolidSm,
		statusNew: false,
	},
	{
		tags: ["external-link", "external", "link"],
		name: "external-link",
		outline: Hero.ExternalLinkOutlineMd,
		solid: Hero.ExternalLinkSolidSm,
		statusNew: false,
	},
	{
		tags: ["eye-off", "eye", "off"],
		name: "eye-off",
		outline: Hero.EyeOffOutlineMd,
		solid: Hero.EyeOffSolidSm,
		statusNew: false,
	},
	{
		tags: ["eye"],
		name: "eye",
		outline: Hero.EyeOutlineMd,
		solid: Hero.EyeSolidSm,
		statusNew: false,
	},
	{
		tags: ["filter"],
		name: "filter",
		outline: Hero.FilterOutlineMd,
		solid: Hero.FilterSolidSm,
		statusNew: false,
	},
	{
		tags: ["fire"],
		name: "fire",
		outline: Hero.FireOutlineMd,
		solid: Hero.FireSolidSm,
		statusNew: true,
	},
	{
		tags: ["flag"],
		name: "flag",
		outline: Hero.FlagOutlineMd,
		solid: Hero.FlagSolidSm,
		statusNew: false,
	},
	{
		tags: ["folder"],
		name: "folder",
		outline: Hero.FolderOutlineMd,
		solid: Hero.FolderSolidSm,
		statusNew: false,
	},
	{
		tags: ["folder-add", "folder", "add"],
		name: "folder-add",
		outline: Hero.FolderAddOutlineMd,
		solid: Hero.FolderAddSolidSm,
		statusNew: true,
	},
	{
		tags: ["folder-download", "folder", "download"],
		name: "folder-download",
		outline: Hero.FolderDownloadOutlineMd,
		solid: Hero.FolderDownloadSolidSm,
		statusNew: true,
	},
	{
		tags: ["folder-remove", "folder", "remove"],
		name: "folder-remove",
		outline: Hero.FolderRemoveOutlineMd,
		solid: Hero.FolderRemoveSolidSm,
		statusNew: true,
	},
	{
		tags: ["globe-alt", "globe", "alt"],
		name: "globe-alt",
		outline: Hero.GlobeAltOutlineMd,
		solid: Hero.GlobeAltSolidSm,
		statusNew: false,
	},
	{
		tags: ["globe"],
		name: "globe",
		outline: Hero.GlobeOutlineMd,
		solid: Hero.GlobeSolidSm,
		statusNew: false,
	},
	{
		tags: ["new", "hand"],
		name: "hand",
		outline: Hero.HandOutlineMd,
		solid: Hero.HandSolidSm,
		statusNew: true,
	},
	{
		tags: ["hashtag"],
		name: "hashtag",
		outline: Hero.HashtagOutlineMd,
		solid: Hero.HashtagSolidSm,
		statusNew: false,
	},
	{
		tags: ["heart"],
		name: "heart",
		outline: Hero.HeartOutlineMd,
		solid: Hero.HeartSolidSm,
		statusNew: false,
	},
	{
		tags: ["home"],
		name: "home",
		outline: Hero.HomeOutlineMd,
		solid: Hero.HomeSolidSm,
		statusNew: false,
	},
	{
		tags: ["inbox-in", "inbox", "in"],
		name: "inbox-in",
		outline: Hero.InboxInOutlineMd,
		solid: Hero.InboxInSolidSm,
		statusNew: false,
	},
	{
		tags: ["inbox"],
		name: "inbox",
		outline: Hero.InboxOutlineMd,
		solid: Hero.InboxSolidSm,
		statusNew: false,
	},
	{
		tags: ["information-circle", "information", "circle"],
		name: "information-circle",
		outline: Hero.InformationCircleOutlineMd,
		solid: Hero.InformationCircleSolidSm,
		statusNew: false,
	},
	{
		tags: ["key"],
		name: "key",
		outline: Hero.KeyOutlineMd,
		solid: Hero.KeySolidSm,
		statusNew: false,
	},
	{
		tags: ["library"],
		name: "library",
		outline: Hero.LibraryOutlineMd,
		solid: Hero.LibrarySolidSm,
		statusNew: false,
	},
	{
		tags: ["light-bulb", "light", "bulb"],
		name: "light-bulb",
		outline: Hero.LightBulbOutlineMd,
		solid: Hero.LightBulbSolidSm,
		statusNew: false,
	},
	{
		tags: ["lightning-bolt", "lightning", "bolt"],
		name: "lightning-bolt",
		outline: Hero.LightningBoltOutlineMd,
		solid: Hero.LightningBoltSolidSm,
		statusNew: false,
	},
	{
		tags: ["link"],
		name: "link",
		outline: Hero.LinkOutlineMd,
		solid: Hero.LinkSolidSm,
		statusNew: false,
	},
	{
		tags: ["location-marker", "location", "marker"],
		name: "location-marker",
		outline: Hero.LocationMarkerOutlineMd,
		solid: Hero.LocationMarkerSolidSm,
		statusNew: false,
	},
	{
		tags: ["lock-closed", "lock", "closed"],
		name: "lock-closed",
		outline: Hero.LockClosedOutlineMd,
		solid: Hero.LockClosedSolidSm,
		statusNew: false,
	},
	{
		tags: ["lock-open", "lock", "open"],
		name: "lock-open",
		outline: Hero.LockOpenOutlineMd,
		solid: Hero.LockOpenSolidSm,
		statusNew: false,
	},
	{
		tags: ["logout"],
		name: "logout",
		outline: Hero.LogoutOutlineMd,
		solid: Hero.LogoutSolidSm,
		statusNew: false,
	},
	{
		tags: ["mail-open", "mail", "open"],
		name: "mail-open",
		outline: Hero.MailOpenOutlineMd,
		solid: Hero.MailOpenSolidSm,
		statusNew: false,
	},
	{
		tags: ["mail"],
		name: "mail",
		outline: Hero.MailOutlineMd,
		solid: Hero.MailSolidSm,
		statusNew: false,
	},
	{
		tags: ["menu-alt1", "menu", "alt1"],
		name: "menu-alt1",
		outline: Hero.MenuAlt1OutlineMd,
		solid: Hero.MenuAlt1SolidSm,
		statusNew: false,
	},
	{
		tags: ["menu-alt2", "menu", "alt2"],
		name: "menu-alt2",
		outline: Hero.MenuAlt2OutlineMd,
		solid: Hero.MenuAlt2SolidSm,
		statusNew: false,
	},
	{
		tags: ["menu-alt3", "menu", "alt3"],
		name: "menu-alt3",
		outline: Hero.MenuAlt3OutlineMd,
		solid: Hero.MenuAlt3SolidSm,
		statusNew: false,
	},
	{
		tags: ["menu-alt4", "menu", "alt4"],
		name: "menu-alt4",
		outline: Hero.MenuAlt4OutlineMd,
		solid: Hero.MenuAlt4SolidSm,
		statusNew: false,
	},
	{
		tags: ["menu"],
		name: "menu",
		outline: Hero.MenuOutlineMd,
		solid: Hero.MenuSolidSm,
		statusNew: false,
	},
	{
		tags: ["microphone"],
		name: "microphone",
		outline: Hero.MicrophoneOutlineMd,
		solid: Hero.MicrophoneSolidSm,
		statusNew: false,
	},
	{
		tags: ["minus-circle", "minus", "circle"],
		name: "minus-circle",
		outline: Hero.MinusCircleOutlineMd,
		solid: Hero.MinusCircleSolidSm,
		statusNew: false,
	},
	{
		tags: ["moon"],
		name: "moon",
		outline: Hero.MoonOutlineMd,
		solid: Hero.MoonSolidSm,
		statusNew: false,
	},
	{
		tags: ["newspaper"],
		name: "newspaper",
		outline: Hero.NewspaperOutlineMd,
		solid: Hero.NewspaperSolidSm,
		statusNew: false,
	},
	{
		tags: ["office-building", "office", "building"],
		name: "office-building",
		outline: Hero.OfficeBuildingOutlineMd,
		solid: Hero.OfficeBuildingSolidSm,
		statusNew: false,
	},
	{
		tags: ["paper-clip", "paper", "clip"],
		name: "paper-clip",
		outline: Hero.PaperClipOutlineMd,
		solid: Hero.PaperClipSolidSm,
		statusNew: false,
	},
	{
		tags: ["pause"],
		name: "pause",
		outline: Hero.PauseOutlineMd,
		solid: Hero.PauseSolidSm,
		statusNew: false,
	},
	{
		tags: ["pencil-alt", "pencil", "alt"],
		name: "pencil-alt",
		outline: Hero.PencilAltOutlineMd,
		solid: Hero.PencilAltSolidSm,
		statusNew: false,
	},
	{
		tags: ["pencil"],
		name: "pencil",
		outline: Hero.PencilOutlineMd,
		solid: Hero.PencilSolidSm,
		statusNew: false,
	},
	{
		tags: ["phone-incoming", "phone", "incoming"],
		name: "phone-incoming",
		outline: Hero.PhoneIncomingOutlineMd,
		solid: Hero.PhoneIncomingSolidSm,
		statusNew: false,
	},
	{
		tags: ["phone-outgoing", "phone", "outgoing"],
		name: "phone-outgoing",
		outline: Hero.PhoneOutgoingOutlineMd,
		solid: Hero.PhoneOutgoingSolidSm,
		statusNew: false,
	},
	{
		tags: ["phone"],
		name: "phone",
		outline: Hero.PhoneOutlineMd,
		solid: Hero.PhoneSolidSm,
		statusNew: false,
	},
	{
		tags: ["photograph"],
		name: "photograph",
		outline: Hero.PhotographOutlineMd,
		solid: Hero.PhotographSolidSm,
		statusNew: false,
	},
	{
		tags: ["play"],
		name: "play",
		outline: Hero.PlayOutlineMd,
		solid: Hero.PlaySolidSm,
		statusNew: false,
	},
	{
		tags: ["plus-circle", "plus", "circle"],
		name: "plus-circle",
		outline: Hero.PlusCircleOutlineMd,
		solid: Hero.PlusCircleSolidSm,
		statusNew: false,
	},
	{
		tags: ["plus"],
		name: "plus",
		outline: Hero.PlusOutlineMd,
		solid: Hero.PlusSolidSm,
		statusNew: false,
	},
	{
		tags: ["printer"],
		name: "printer",
		outline: Hero.PrinterOutlineMd,
		solid: Hero.PrinterSolidSm,
		statusNew: false,
	},
	{
		tags: ["new", "puzzle"],
		name: "puzzle",
		outline: Hero.PuzzleOutlineMd,
		solid: Hero.PuzzleSolidSm,
		statusNew: true,
	},
	{
		tags: ["q-r-code", "q", "r", "code"],
		name: "q-r-code",
		outline: Hero.QRCodeOutlineMd,
		solid: Hero.QRCodeSolidSm,
		statusNew: false,
	},
	{
		tags: ["question-mark-circle", "question", "mark", "circle"],
		name: "question-mark-circle",
		outline: Hero.QuestionMarkCircleOutlineMd,
		solid: Hero.QuestionMarkCircleSolidSm,
		statusNew: false,
	},
	{
		tags: ["receipt-refund", "receipt", "refund"],
		name: "receipt-refund",
		outline: Hero.ReceiptRefundOutlineMd,
		solid: Hero.ReceiptRefundSolidSm,
		statusNew: false,
	},
	{
		tags: ["refresh"],
		name: "refresh",
		outline: Hero.RefreshOutlineMd,
		solid: Hero.RefreshSolidSm,
		statusNew: false,
	},
	{
		tags: ["reply"],
		name: "reply",
		outline: Hero.ReplyOutlineMd,
		solid: Hero.ReplySolidSm,
		statusNew: false,
	},
	{
		tags: ["scale"],
		name: "scale",
		outline: Hero.ScaleOutlineMd,
		solid: Hero.ScaleSolidSm,
		statusNew: false,
	},
	{
		tags: ["search"],
		name: "search",
		outline: Hero.SearchOutlineMd,
		solid: Hero.SearchSolidSm,
		statusNew: false,
	},
	{
		tags: ["selector"],
		name: "selector",
		outline: Hero.SelectorOutlineMd,
		solid: Hero.SelectorSolidSm,
		statusNew: false,
	},
	{
		tags: ["share"],
		name: "share",
		outline: Hero.ShareOutlineMd,
		solid: Hero.ShareSolidSm,
		statusNew: false,
	},
	{
		tags: ["shield-check", "shield", "check"],
		name: "shield-check",
		outline: Hero.ShieldCheckOutlineMd,
		solid: Hero.ShieldCheckSolidSm,
		statusNew: false,
	},
	{
		tags: ["shield-exclamation", "shield", "exclamation"],
		name: "shield-exclamation",
		outline: Hero.ShieldExclamationOutlineMd,
		solid: Hero.ShieldExclamationSolidSm,
		statusNew: false,
	},
	{
		tags: ["shopping-bag", "shopping", "bag"],
		name: "shopping-bag",
		outline: Hero.ShoppingBagOutlineMd,
		solid: Hero.ShoppingBagSolidSm,
		statusNew: true,
	},
	{
		tags: ["shopping-cart", "shopping", "cart"],
		name: "shopping-cart",
		outline: Hero.ShoppingCartOutlineMd,
		solid: Hero.ShoppingCartSolidSm,
		statusNew: false,
	},
	{
		tags: ["sort-ascending", "sort", "ascending"],
		name: "sort-ascending",
		outline: Hero.SortAscendingOutlineMd,
		solid: Hero.SortAscendingSolidSm,
		statusNew: false,
	},
	{
		tags: ["sort-descending", "sort", "descending"],
		name: "sort-descending",
		outline: Hero.SortDescendingOutlineMd,
		solid: Hero.SortDescendingSolidSm,
		statusNew: false,
	},
	{
		tags: ["sparkles"],
		name: "sparkles",
		outline: Hero.SparklesOutlineMd,
		solid: Hero.SparklesSolidSm,
		statusNew: false,
	},
	{
		tags: ["speakerphone"],
		name: "speakerphone",
		outline: Hero.SpeakerphoneOutlineMd,
		solid: Hero.SpeakerphoneSolidSm,
		statusNew: false,
	},
	{
		tags: ["star"],
		name: "star",
		outline: Hero.StarOutlineMd,
		solid: Hero.StarSolidSm,
		statusNew: false,
	},
	{
		tags: ["stop"],
		name: "stop",
		outline: Hero.StopOutlineMd,
		solid: Hero.StopSolidSm,
		statusNew: false,
	},
	{
		tags: ["sun"],
		name: "sun",
		outline: Hero.SunOutlineMd,
		solid: Hero.SunSolidSm,
		statusNew: false,
	},
	{
		tags: ["support"],
		name: "support",
		outline: Hero.SupportOutlineMd,
		solid: Hero.SupportSolidSm,
		statusNew: false,
	},
	{
		tags: ["switch-horizontal", "switch", "horizontal"],
		name: "switch-horizontal",
		outline: Hero.SwitchHorizontalOutlineMd,
		solid: Hero.SwitchHorizontalSolidSm,
		statusNew: false,
	},
	{
		tags: ["switch-vertical", "switch", "vertical"],
		name: "switch-vertical",
		outline: Hero.SwitchVerticalOutlineMd,
		solid: Hero.SwitchVerticalSolidSm,
		statusNew: false,
	},
	{
		tags: ["tag"],
		name: "tag",
		outline: Hero.TagOutlineMd,
		solid: Hero.TagSolidSm,
		statusNew: false,
	},
	{
		tags: ["template"],
		name: "template",
		outline: Hero.TemplateOutlineMd,
		solid: Hero.TemplateSolidSm,
		statusNew: false,
	},
	{
		tags: ["terminal"],
		name: "terminal",
		outline: Hero.TerminalOutlineMd,
		solid: Hero.TerminalSolidSm,
		statusNew: false,
	},
	{
		tags: ["new", "thumb-down", "thumb", "down"],
		name: "thumb-down",
		outline: Hero.ThumbDownOutlineMd,
		solid: Hero.ThumbDownSolidSm,
		statusNew: true,
	},
	{
		tags: ["new", "thumb-up", "thumb", "up"],
		name: "thumb-up",
		outline: Hero.ThumbUpOutlineMd,
		solid: Hero.ThumbUpSolidSm,
		statusNew: true,
	},
	{
		tags: ["ticket"],
		name: "ticket",
		outline: Hero.TicketOutlineMd,
		solid: Hero.TicketSolidSm,
		statusNew: false,
	},
	{
		tags: ["translate"],
		name: "translate",
		outline: Hero.TranslateOutlineMd,
		solid: Hero.TranslateSolidSm,
		statusNew: false,
	},
	{
		tags: ["trash"],
		name: "trash",
		outline: Hero.TrashOutlineMd,
		solid: Hero.TrashSolidSm,
		statusNew: false,
	},
	{
		tags: ["trending-down", "trending", "down"],
		name: "trending-down",
		outline: Hero.TrendingDownOutlineMd,
		solid: Hero.TrendingDownSolidSm,
		statusNew: false,
	},
	{
		tags: ["trending-up", "trending", "up"],
		name: "trending-up",
		outline: Hero.TrendingUpOutlineMd,
		solid: Hero.TrendingUpSolidSm,
		statusNew: false,
	},
	{
		tags: ["upload"],
		name: "upload",
		outline: Hero.UploadOutlineMd,
		solid: Hero.UploadSolidSm,
		statusNew: false,
	},
	{
		tags: ["user-add", "user", "add"],
		name: "user-add",
		outline: Hero.UserAddOutlineMd,
		solid: Hero.UserAddSolidSm,
		statusNew: false,
	},
	{
		tags: ["user-circle", "user", "circle"],
		name: "user-circle",
		outline: Hero.UserCircleOutlineMd,
		solid: Hero.UserCircleSolidSm,
		statusNew: false,
	},
	{
		tags: ["user-group", "user", "group"],
		name: "user-group",
		outline: Hero.UserGroupOutlineMd,
		solid: Hero.UserGroupSolidSm,
		statusNew: false,
	},
	{
		tags: ["user-remove", "user", "remove"],
		name: "user-remove",
		outline: Hero.UserRemoveOutlineMd,
		solid: Hero.UserRemoveSolidSm,
		statusNew: false,
	},
	{
		tags: ["user"],
		name: "user",
		outline: Hero.UserOutlineMd,
		solid: Hero.UserSolidSm,
		statusNew: false,
	},
	{
		tags: ["users"],
		name: "users",
		outline: Hero.UsersOutlineMd,
		solid: Hero.UsersSolidSm,
		statusNew: false,
	},
	{
		tags: ["view-boards", "view", "boards"],
		name: "view-boards",
		outline: Hero.ViewBoardsOutlineMd,
		solid: Hero.ViewBoardsSolidSm,
		statusNew: false,
	},
	{
		tags: ["view-grid-add", "view", "grid", "add"],
		name: "view-grid-add",
		outline: Hero.ViewGridAddOutlineMd,
		solid: Hero.ViewGridAddSolidSm,
		statusNew: false,
	},
	{
		tags: ["new", "view-grid", "view", "grid"],
		name: "view-grid",
		outline: Hero.ViewGridOutlineMd,
		solid: Hero.ViewGridSolidSm,
		statusNew: true,
	},
	{
		tags: ["view-list", "view", "list"],
		name: "view-list",
		outline: Hero.ViewListOutlineMd,
		solid: Hero.ViewListSolidSm,
		statusNew: false,
	},
	{
		tags: ["volume-off", "volume", "off"],
		name: "volume-off",
		outline: Hero.VolumeOffOutlineMd,
		solid: Hero.VolumeOffSolidSm,
		statusNew: false,
	},
	{
		tags: ["volume-up", "volume", "up"],
		name: "volume-up",
		outline: Hero.VolumeUpOutlineMd,
		solid: Hero.VolumeUpSolidSm,
		statusNew: false,
	},
	{
		tags: ["x-circle", "x", "circle"],
		name: "x-circle",
		outline: Hero.XCircleOutlineMd,
		solid: Hero.XCircleSolidSm,
		statusNew: false,
	},
	{
		tags: ["x"],
		name: "x",
		outline: Hero.XOutlineMd,
		solid: Hero.XSolidSm,
		statusNew: false,
	},
	{
		tags: ["zoom-in", "zoom", "in"],
		name: "zoom-in",
		outline: Hero.ZoomInOutlineMd,
		solid: Hero.ZoomInSolidSm,
		statusNew: false,
	},
	{
		tags: ["zoom-out", "zoom", "out"],
		name: "zoom-out",
		outline: Hero.ZoomOutOutlineMd,
		solid: Hero.ZoomOutSolidSm,
		statusNew: false,
	},
]

export default originalIcons
