import * as Outline from "react-ecfba30/outline"
import * as Solid from "react-ecfba30/solid"

const icons = [
	{
		name: "academic-cap",
		outline: Outline.AcademicCap,
		solid: Solid.AcademicCap,
		statusNew: false,
	},
	{
		name: "adjustments",
		outline: Outline.Adjustments,
		solid: Solid.Adjustments,
		statusNew: false,
	},
	{
		name: "annotation",
		outline: Outline.Annotation,
		solid: Solid.Annotation,
		statusNew: false,
	},
	{
		name: "archive",
		outline: Outline.Archive,
		solid: Solid.Archive,
		statusNew: false,
	},
	{
		name: "arrow-circle-down",
		outline: Outline.ArrowCircleDown,
		solid: Solid.ArrowCircleDown,
		statusNew: false,
	},
	{
		name: "arrow-circle-left",
		outline: Outline.ArrowCircleLeft,
		solid: Solid.ArrowCircleLeft,
		statusNew: false,
	},
	{
		name: "arrow-circle-right",
		outline: Outline.ArrowCircleRight,
		solid: Solid.ArrowCircleRight,
		statusNew: false,
	},
	{
		name: "arrow-circle-up",
		outline: Outline.ArrowCircleUp,
		solid: Solid.ArrowCircleUp,
		statusNew: false,
	},
	{
		name: "arrow-down",
		outline: Outline.ArrowDown,
		solid: Solid.ArrowDown,
		statusNew: false,
	},
	{
		name: "arrow-left",
		outline: Outline.ArrowLeft,
		solid: Solid.ArrowLeft,
		statusNew: false,
	},
	{
		name: "arrow-narrow-down",
		outline: Outline.ArrowNarrowDown,
		solid: Solid.ArrowNarrowDown,
		statusNew: false,
	},
	{
		name: "arrow-narrow-left",
		outline: Outline.ArrowNarrowLeft,
		solid: Solid.ArrowNarrowLeft,
		statusNew: false,
	},
	{
		name: "arrow-narrow-right",
		outline: Outline.ArrowNarrowRight,
		solid: Solid.ArrowNarrowRight,
		statusNew: false,
	},
	{
		name: "arrow-narrow-up",
		outline: Outline.ArrowNarrowUp,
		solid: Solid.ArrowNarrowUp,
		statusNew: false,
	},
	{
		name: "arrow-right",
		outline: Outline.ArrowRight,
		solid: Solid.ArrowRight,
		statusNew: false,
	},
	{
		name: "arrows-expand",
		outline: Outline.ArrowsExpand,
		solid: Solid.ArrowsExpand,
		statusNew: false,
	},
	{
		name: "arrow-up",
		outline: Outline.ArrowUp,
		solid: Solid.ArrowUp,
		statusNew: false,
	},
	{
		name: "at-symbol",
		outline: Outline.AtSymbol,
		solid: Solid.AtSymbol,
		statusNew: false,
	},
	{
		name: "backspace",
		outline: Outline.Backspace,
		solid: Solid.Backspace,
		statusNew: false,
	},
	{
		name: "badge-check",
		outline: Outline.BadgeCheck,
		solid: Solid.BadgeCheck,
		statusNew: false,
	},
	{
		name: "ban",
		outline: Outline.Ban,
		solid: Solid.Ban,
		statusNew: false,
	},
	{
		name: "beaker",
		outline: Outline.Beaker,
		solid: Solid.Beaker,
		statusNew: false,
	},
	{
		name: "bell",
		outline: Outline.Bell,
		solid: Solid.Bell,
		statusNew: false,
	},
	{
		name: "bookmark",
		outline: Outline.Bookmark,
		solid: Solid.Bookmark,
		statusNew: false,
	},
	{
		name: "bookmark-alt",
		outline: Outline.BookmarkAlt,
		solid: Solid.BookmarkAlt,
		statusNew: false,
	},
	{
		name: "book-open",
		outline: Outline.BookOpen,
		solid: Solid.BookOpen,
		statusNew: false,
	},
	{
		name: "briefcase",
		outline: Outline.Briefcase,
		solid: Solid.Briefcase,
		statusNew: false,
	},
	{
		name: "cake",
		outline: Outline.Cake,
		solid: Solid.Cake,
		statusNew: false,
	},
	{
		name: "calculator",
		outline: Outline.Calculator,
		solid: Solid.Calculator,
		statusNew: false,
	},
	{
		name: "calendar",
		outline: Outline.Calendar,
		solid: Solid.Calendar,
		statusNew: false,
	},
	{
		name: "camera",
		outline: Outline.Camera,
		solid: Solid.Camera,
		statusNew: false,
	},
	{
		name: "cash",
		outline: Outline.Cash,
		solid: Solid.Cash,
		statusNew: false,
	},
	{
		name: "chart-bar",
		outline: Outline.ChartBar,
		solid: Solid.ChartBar,
		statusNew: false,
	},
	{
		name: "chart-pie",
		outline: Outline.ChartPie,
		solid: Solid.ChartPie,
		statusNew: false,
	},
	{
		name: "chart-square-bar",
		outline: Outline.ChartSquareBar,
		solid: Solid.ChartSquareBar,
		statusNew: false,
	},
	{
		name: "chat",
		outline: Outline.Chat,
		solid: Solid.Chat,
		statusNew: false,
	},
	{
		name: "chat-alt",
		outline: Outline.ChatAlt,
		solid: Solid.ChatAlt,
		statusNew: false,
	},
	{
		name: "chat-alt2",
		outline: Outline.ChatAlt2,
		solid: Solid.ChatAlt2,
		statusNew: false,
	},
	{
		name: "check",
		outline: Outline.Check,
		solid: Solid.Check,
		statusNew: false,
	},
	{
		name: "check-circle",
		outline: Outline.CheckCircle,
		solid: Solid.CheckCircle,
		statusNew: false,
	},
	{
		name: "chevron-double-down",
		outline: Outline.ChevronDoubleDown,
		solid: Solid.ChevronDoubleDown,
		statusNew: false,
	},
	{
		name: "chevron-double-left",
		outline: Outline.ChevronDoubleLeft,
		solid: Solid.ChevronDoubleLeft,
		statusNew: false,
	},
	{
		name: "chevron-double-right",
		outline: Outline.ChevronDoubleRight,
		solid: Solid.ChevronDoubleRight,
		statusNew: false,
	},
	{
		name: "chevron-double-up",
		outline: Outline.ChevronDoubleUp,
		solid: Solid.ChevronDoubleUp,
		statusNew: false,
	},
	{
		name: "chevron-down",
		outline: Outline.ChevronDown,
		solid: Solid.ChevronDown,
		statusNew: false,
	},
	{
		name: "chevron-left",
		outline: Outline.ChevronLeft,
		solid: Solid.ChevronLeft,
		statusNew: false,
	},
	{
		name: "chevron-right",
		outline: Outline.ChevronRight,
		solid: Solid.ChevronRight,
		statusNew: false,
	},
	{
		name: "chevron-up",
		outline: Outline.ChevronUp,
		solid: Solid.ChevronUp,
		statusNew: false,
	},
	{
		name: "chip",
		outline: Outline.Chip,
		solid: Solid.Chip,
		statusNew: false,
	},
	{
		name: "clipboard",
		outline: Outline.Clipboard,
		solid: Solid.Clipboard,
		statusNew: false,
	},
	{
		name: "clipboard-check",
		outline: Outline.ClipboardCheck,
		solid: Solid.ClipboardCheck,
		statusNew: false,
	},
	{
		name: "clipboard-copy",
		outline: Outline.ClipboardCopy,
		solid: Solid.ClipboardCopy,
		statusNew: false,
	},
	{
		name: "clipboard-list",
		outline: Outline.ClipboardList,
		solid: Solid.ClipboardList,
		statusNew: false,
	},
	{
		name: "clock",
		outline: Outline.Clock,
		solid: Solid.Clock,
		statusNew: false,
	},
	{
		name: "cloud",
		outline: Outline.Cloud,
		solid: Solid.Cloud,
		statusNew: false,
	},
	{
		name: "cloud-download",
		outline: Outline.CloudDownload,
		solid: Solid.CloudDownload,
		statusNew: false,
	},
	{
		name: "cloud-upload",
		outline: Outline.CloudUpload,
		solid: Solid.CloudUpload,
		statusNew: false,
	},
	{
		name: "code",
		outline: Outline.Code,
		solid: Solid.Code,
		statusNew: false,
	},
	{
		name: "cog",
		outline: Outline.Cog,
		solid: Solid.Cog,
		statusNew: false,
	},
	{
		name: "collection",
		outline: Outline.Collection,
		solid: Solid.Collection,
		statusNew: false,
	},
	{
		name: "color-swatch",
		outline: Outline.ColorSwatch,
		solid: Solid.ColorSwatch,
		statusNew: false,
	},
	{
		name: "credit-card",
		outline: Outline.CreditCard,
		solid: Solid.CreditCard,
		statusNew: false,
	},
	{
		name: "cube",
		outline: Outline.Cube,
		solid: Solid.Cube,
		statusNew: false,
	},
	{
		name: "cube-transparent",
		outline: Outline.CubeTransparent,
		solid: Solid.CubeTransparent,
		statusNew: false,
	},
	{
		name: "currency-bangladeshi",
		outline: Outline.CurrencyBangladeshi,
		solid: Solid.CurrencyBangladeshi,
		statusNew: false,
	},
	{
		name: "currency-dollar",
		outline: Outline.CurrencyDollar,
		solid: Solid.CurrencyDollar,
		statusNew: false,
	},
	{
		name: "currency-euro",
		outline: Outline.CurrencyEuro,
		solid: Solid.CurrencyEuro,
		statusNew: false,
	},
	{
		name: "currency-pound",
		outline: Outline.CurrencyPound,
		solid: Solid.CurrencyPound,
		statusNew: false,
	},
	{
		name: "currency-rupee",
		outline: Outline.CurrencyRupee,
		solid: Solid.CurrencyRupee,
		statusNew: false,
	},
	{
		name: "currency-yen",
		outline: Outline.CurrencyYen,
		solid: Solid.CurrencyYen,
		statusNew: false,
	},
	{
		name: "cursor-click",
		outline: Outline.CursorClick,
		solid: Solid.CursorClick,
		statusNew: false,
	},
	{
		name: "database",
		outline: Outline.Database,
		solid: Solid.Database,
		statusNew: false,
	},
	{
		name: "desktop-computer",
		outline: Outline.DesktopComputer,
		solid: Solid.DesktopComputer,
		statusNew: false,
	},
	{
		name: "device-mobile",
		outline: Outline.DeviceMobile,
		solid: Solid.DeviceMobile,
		statusNew: false,
	},
	{
		name: "device-tablet",
		outline: Outline.DeviceTablet,
		solid: Solid.DeviceTablet,
		statusNew: false,
	},
	{
		name: "document",
		outline: Outline.Document,
		solid: Solid.Document,
		statusNew: false,
	},
	{
		name: "document-add",
		outline: Outline.DocumentAdd,
		solid: Solid.DocumentAdd,
		statusNew: false,
	},
	{
		name: "document-download",
		outline: Outline.DocumentDownload,
		solid: Solid.DocumentDownload,
		statusNew: false,
	},
	{
		name: "document-duplicate",
		outline: Outline.DocumentDuplicate,
		solid: Solid.DocumentDuplicate,
		statusNew: false,
	},
	{
		name: "document-remove",
		outline: Outline.DocumentRemove,
		solid: Solid.DocumentRemove,
		statusNew: false,
	},
	{
		name: "document-report",
		outline: Outline.DocumentReport,
		solid: Solid.DocumentReport,
		statusNew: false,
	},
	{
		name: "document-search",
		outline: Outline.DocumentSearch,
		solid: Solid.DocumentSearch,
		statusNew: false,
	},
	{
		name: "document-text",
		outline: Outline.DocumentText,
		solid: Solid.DocumentText,
		statusNew: false,
	},
	{
		name: "dots-circle-horizontal",
		outline: Outline.DotsCircleHorizontal,
		solid: Solid.DotsCircleHorizontal,
		statusNew: false,
	},
	{
		name: "dots-horizontal",
		outline: Outline.DotsHorizontal,
		solid: Solid.DotsHorizontal,
		statusNew: false,
	},
	{
		name: "dots-vertical",
		outline: Outline.DotsVertical,
		solid: Solid.DotsVertical,
		statusNew: false,
	},
	{
		name: "download",
		outline: Outline.Download,
		solid: Solid.Download,
		statusNew: false,
	},
	{
		name: "duplicate",
		outline: Outline.Duplicate,
		solid: Solid.Duplicate,
		statusNew: false,
	},
	{
		name: "emoji-happy",
		outline: Outline.EmojiHappy,
		solid: Solid.EmojiHappy,
		statusNew: false,
	},
	{
		name: "emoji-sad",
		outline: Outline.EmojiSad,
		solid: Solid.EmojiSad,
		statusNew: false,
	},
	{
		name: "exclamation",
		outline: Outline.Exclamation,
		solid: Solid.Exclamation,
		statusNew: false,
	},
	{
		name: "exclamation-circle",
		outline: Outline.ExclamationCircle,
		solid: Solid.ExclamationCircle,
		statusNew: false,
	},
	{
		name: "external-link",
		outline: Outline.ExternalLink,
		solid: Solid.ExternalLink,
		statusNew: false,
	},
	{
		name: "eye",
		outline: Outline.Eye,
		solid: Solid.Eye,
		statusNew: false,
	},
	{
		name: "eye-off",
		outline: Outline.EyeOff,
		solid: Solid.EyeOff,
		statusNew: false,
	},
	{
		name: "fast-forward",
		outline: Outline.FastForward,
		solid: Solid.FastForward,
		statusNew: false,
	},
	{
		name: "film",
		outline: Outline.Film,
		solid: Solid.Film,
		statusNew: false,
	},
	{
		name: "filter",
		outline: Outline.Filter,
		solid: Solid.Filter,
		statusNew: false,
	},
	{
		name: "finger-print",
		outline: Outline.FingerPrint,
		solid: Solid.FingerPrint,
		statusNew: false,
	},
	{
		name: "fire",
		outline: Outline.Fire,
		solid: Solid.Fire,
		statusNew: false,
	},
	{
		name: "flag",
		outline: Outline.Flag,
		solid: Solid.Flag,
		statusNew: false,
	},
	{
		name: "folder",
		outline: Outline.Folder,
		solid: Solid.Folder,
		statusNew: false,
	},
	{
		name: "folder-add",
		outline: Outline.FolderAdd,
		solid: Solid.FolderAdd,
		statusNew: false,
	},
	{
		name: "folder-download",
		outline: Outline.FolderDownload,
		solid: Solid.FolderDownload,
		statusNew: false,
	},
	{
		name: "folder-open",
		outline: Outline.FolderOpen,
		solid: Solid.FolderOpen,
		statusNew: false,
	},
	{
		name: "folder-remove",
		outline: Outline.FolderRemove,
		solid: Solid.FolderRemove,
		statusNew: false,
	},
	{
		name: "gift",
		outline: Outline.Gift,
		solid: Solid.Gift,
		statusNew: false,
	},
	{
		name: "globe",
		outline: Outline.Globe,
		solid: Solid.Globe,
		statusNew: false,
	},
	{
		name: "globe-alt",
		outline: Outline.GlobeAlt,
		solid: Solid.GlobeAlt,
		statusNew: false,
	},
	{
		name: "hand",
		outline: Outline.Hand,
		solid: Solid.Hand,
		statusNew: false,
	},
	{
		name: "hashtag",
		outline: Outline.Hashtag,
		solid: Solid.Hashtag,
		statusNew: false,
	},
	{
		name: "heart",
		outline: Outline.Heart,
		solid: Solid.Heart,
		statusNew: false,
	},
	{
		name: "home",
		outline: Outline.Home,
		solid: Solid.Home,
		statusNew: false,
	},
	{
		name: "identification",
		outline: Outline.Identification,
		solid: Solid.Identification,
		statusNew: false,
	},
	{
		name: "inbox",
		outline: Outline.Inbox,
		solid: Solid.Inbox,
		statusNew: false,
	},
	{
		name: "inbox-in",
		outline: Outline.InboxIn,
		solid: Solid.InboxIn,
		statusNew: false,
	},
	index.js
	{
		name: "information-circle",
		outline: Outline.InformationCircle,
		solid: Solid.InformationCircle,
		statusNew: false,
	},
	{
		name: "key",
		outline: Outline.Key,
		solid: Solid.Key,
		statusNew: false,
	},
	{
		name: "library",
		outline: Outline.Library,
		solid: Solid.Library,
		statusNew: false,
	},
	{
		name: "light-bulb",
		outline: Outline.LightBulb,
		solid: Solid.LightBulb,
		statusNew: false,
	},
	{
		name: "lightning-bolt",
		outline: Outline.LightningBolt,
		solid: Solid.LightningBolt,
		statusNew: false,
	},
	{
		name: "link",
		outline: Outline.Link,
		solid: Solid.Link,
		statusNew: false,
	},
	{
		name: "location-marker",
		outline: Outline.LocationMarker,
		solid: Solid.LocationMarker,
		statusNew: false,
	},
	{
		name: "lock-closed",
		outline: Outline.LockClosed,
		solid: Solid.LockClosed,
		statusNew: false,
	},
	{
		name: "lock-open",
		outline: Outline.LockOpen,
		solid: Solid.LockOpen,
		statusNew: false,
	},
	{
		name: "login",
		outline: Outline.Login,
		solid: Solid.Login,
		statusNew: false,
	},
	{
		name: "logout",
		outline: Outline.Logout,
		solid: Solid.Logout,
		statusNew: false,
	},
	{
		name: "mail",
		outline: Outline.Mail,
		solid: Solid.Mail,
		statusNew: false,
	},
	{
		name: "mail-open",
		outline: Outline.MailOpen,
		solid: Solid.MailOpen,
		statusNew: false,
	},
	{
		name: "map",
		outline: Outline.Map,
		solid: Solid.Map,
		statusNew: false,
	},
	{
		name: "menu",
		outline: Outline.Menu,
		solid: Solid.Menu,
		statusNew: false,
	},
	{
		name: "menu-alt1",
		outline: Outline.MenuAlt1,
		solid: Solid.MenuAlt1,
		statusNew: false,
	},
	{
		name: "menu-alt2",
		outline: Outline.MenuAlt2,
		solid: Solid.MenuAlt2,
		statusNew: false,
	},
	{
		name: "menu-alt3",
		outline: Outline.MenuAlt3,
		solid: Solid.MenuAlt3,
		statusNew: false,
	},
	{
		name: "menu-alt4",
		outline: Outline.MenuAlt4,
		solid: Solid.MenuAlt4,
		statusNew: false,
	},
	{
		name: "microphone",
		outline: Outline.Microphone,
		solid: Solid.Microphone,
		statusNew: false,
	},
	{
		name: "minus",
		outline: Outline.Minus,
		solid: Solid.Minus,
		statusNew: false,
	},
	{
		name: "minus-circle",
		outline: Outline.MinusCircle,
		solid: Solid.MinusCircle,
		statusNew: false,
	},
	{
		name: "moon",
		outline: Outline.Moon,
		solid: Solid.Moon,
		statusNew: false,
	},
	{
		name: "music-note",
		outline: Outline.MusicNote,
		solid: Solid.MusicNote,
		statusNew: false,
	},
	{
		name: "newspaper",
		outline: Outline.Newspaper,
		solid: Solid.Newspaper,
		statusNew: false,
	},
	{
		name: "office-building",
		outline: Outline.OfficeBuilding,
		solid: Solid.OfficeBuilding,
		statusNew: false,
	},
	{
		name: "paper-airplane",
		outline: Outline.PaperAirplane,
		solid: Solid.PaperAirplane,
		statusNew: false,
	},
	{
		name: "paper-clip",
		outline: Outline.PaperClip,
		solid: Solid.PaperClip,
		statusNew: false,
	},
	{
		name: "pause",
		outline: Outline.Pause,
		solid: Solid.Pause,
		statusNew: false,
	},
	{
		name: "pencil",
		outline: Outline.Pencil,
		solid: Solid.Pencil,
		statusNew: false,
	},
	{
		name: "pencil-alt",
		outline: Outline.PencilAlt,
		solid: Solid.PencilAlt,
		statusNew: false,
	},
	{
		name: "phone",
		outline: Outline.Phone,
		solid: Solid.Phone,
		statusNew: false,
	},
	{
		name: "phone-incoming",
		outline: Outline.PhoneIncoming,
		solid: Solid.PhoneIncoming,
		statusNew: false,
	},
	{
		name: "phone-missed-call",
		outline: Outline.PhoneMissedCall,
		solid: Solid.PhoneMissedCall,
		statusNew: false,
	},
	{
		name: "phone-outgoing",
		outline: Outline.PhoneOutgoing,
		solid: Solid.PhoneOutgoing,
		statusNew: false,
	},
	{
		name: "photograph",
		outline: Outline.Photograph,
		solid: Solid.Photograph,
		statusNew: false,
	},
	{
		name: "play",
		outline: Outline.Play,
		solid: Solid.Play,
		statusNew: false,
	},
	{
		name: "plus",
		outline: Outline.Plus,
		solid: Solid.Plus,
		statusNew: false,
	},
	{
		name: "plus-circle",
		outline: Outline.PlusCircle,
		solid: Solid.PlusCircle,
		statusNew: false,
	},
	{
		name: "presentation-chart-bar",
		outline: Outline.PresentationChartBar,
		solid: Solid.PresentationChartBar,
		statusNew: false,
	},
	{
		name: "presentation-chart-line",
		outline: Outline.PresentationChartLine,
		solid: Solid.PresentationChartLine,
		statusNew: false,
	},
	{
		name: "printer",
		outline: Outline.Printer,
		solid: Solid.Printer,
		statusNew: false,
	},
	{
		name: "puzzle",
		outline: Outline.Puzzle,
		solid: Solid.Puzzle,
		statusNew: false,
	},
	{
		name: "qrcode",
		outline: Outline.Qrcode,
		solid: Solid.Qrcode,
		statusNew: false,
	},
	{
		name: "question-mark-circle",
		outline: Outline.QuestionMarkCircle,
		solid: Solid.QuestionMarkCircle,
		statusNew: false,
	},
	{
		name: "receipt-refund",
		outline: Outline.ReceiptRefund,
		solid: Solid.ReceiptRefund,
		statusNew: false,
	},
	{
		name: "receipt-tax",
		outline: Outline.ReceiptTax,
		solid: Solid.ReceiptTax,
		statusNew: false,
	},
	{
		name: "refresh",
		outline: Outline.Refresh,
		solid: Solid.Refresh,
		statusNew: false,
	},
	{
		name: "reply",
		outline: Outline.Reply,
		solid: Solid.Reply,
		statusNew: false,
	},
	{
		name: "rewind",
		outline: Outline.Rewind,
		solid: Solid.Rewind,
		statusNew: false,
	},
	{
		name: "rss",
		outline: Outline.Rss,
		solid: Solid.Rss,
		statusNew: false,
	},
	{
		name: "save",
		outline: Outline.Save,
		solid: Solid.Save,
		statusNew: false,
	},
	{
		name: "save-as",
		outline: Outline.SaveAs,
		solid: Solid.SaveAs,
		statusNew: false,
	},
	{
		name: "scale",
		outline: Outline.Scale,
		solid: Solid.Scale,
		statusNew: false,
	},
	{
		name: "scissors",
		outline: Outline.Scissors,
		solid: Solid.Scissors,
		statusNew: false,
	},
	{
		name: "search",
		outline: Outline.Search,
		solid: Solid.Search,
		statusNew: false,
	},
	{
		name: "search-circle",
		outline: Outline.SearchCircle,
		solid: Solid.SearchCircle,
		statusNew: false,
	},
	{
		name: "selector",
		outline: Outline.Selector,
		solid: Solid.Selector,
		statusNew: false,
	},
	{
		name: "server",
		outline: Outline.Server,
		solid: Solid.Server,
		statusNew: false,
	},
	{
		name: "share",
		outline: Outline.Share,
		solid: Solid.Share,
		statusNew: false,
	},
	{
		name: "shield-check",
		outline: Outline.ShieldCheck,
		solid: Solid.ShieldCheck,
		statusNew: false,
	},
	{
		name: "shield-exclamation",
		outline: Outline.ShieldExclamation,
		solid: Solid.ShieldExclamation,
		statusNew: false,
	},
	{
		name: "shopping-bag",
		outline: Outline.ShoppingBag,
		solid: Solid.ShoppingBag,
		statusNew: false,
	},
	{
		name: "shopping-cart",
		outline: Outline.ShoppingCart,
		solid: Solid.ShoppingCart,
		statusNew: false,
	},
	{
		name: "sort-ascending",
		outline: Outline.SortAscending,
		solid: Solid.SortAscending,
		statusNew: false,
	},
	{
		name: "sort-descending",
		outline: Outline.SortDescending,
		solid: Solid.SortDescending,
		statusNew: false,
	},
	{
		name: "sparkles",
		outline: Outline.Sparkles,
		solid: Solid.Sparkles,
		statusNew: false,
	},
	{
		name: "speakerphone",
		outline: Outline.Speakerphone,
		solid: Solid.Speakerphone,
		statusNew: false,
	},
	{
		name: "star",
		outline: Outline.Star,
		solid: Solid.Star,
		statusNew: false,
	},
	{
		name: "status-offline",
		outline: Outline.StatusOffline,
		solid: Solid.StatusOffline,
		statusNew: false,
	},
	{
		name: "status-online",
		outline: Outline.StatusOnline,
		solid: Solid.StatusOnline,
		statusNew: false,
	},
	{
		name: "stop",
		outline: Outline.Stop,
		solid: Solid.Stop,
		statusNew: false,
	},
	{
		name: "sun",
		outline: Outline.Sun,
		solid: Solid.Sun,
		statusNew: false,
	},
	{
		name: "support",
		outline: Outline.Support,
		solid: Solid.Support,
		statusNew: false,
	},
	{
		name: "switch-horizontal",
		outline: Outline.SwitchHorizontal,
		solid: Solid.SwitchHorizontal,
		statusNew: false,
	},
	{
		name: "switch-vertical",
		outline: Outline.SwitchVertical,
		solid: Solid.SwitchVertical,
		statusNew: false,
	},
	{
		name: "table",
		outline: Outline.Table,
		solid: Solid.Table,
		statusNew: false,
	},
	{
		name: "tag",
		outline: Outline.Tag,
		solid: Solid.Tag,
		statusNew: false,
	},
	{
		name: "template",
		outline: Outline.Template,
		solid: Solid.Template,
		statusNew: false,
	},
	{
		name: "terminal",
		outline: Outline.Terminal,
		solid: Solid.Terminal,
		statusNew: false,
	},
	{
		name: "thumb-down",
		outline: Outline.ThumbDown,
		solid: Solid.ThumbDown,
		statusNew: false,
	},
	{
		name: "thumb-up",
		outline: Outline.ThumbUp,
		solid: Solid.ThumbUp,
		statusNew: false,
	},
	{
		name: "ticket",
		outline: Outline.Ticket,
		solid: Solid.Ticket,
		statusNew: false,
	},
	{
		name: "translate",
		outline: Outline.Translate,
		solid: Solid.Translate,
		statusNew: false,
	},
	{
		name: "trash",
		outline: Outline.Trash,
		solid: Solid.Trash,
		statusNew: false,
	},
	{
		name: "trending-down",
		outline: Outline.TrendingDown,
		solid: Solid.TrendingDown,
		statusNew: false,
	},
	{
		name: "trending-up",
		outline: Outline.TrendingUp,
		solid: Solid.TrendingUp,
		statusNew: false,
	},
	{
		name: "truck",
		outline: Outline.Truck,
		solid: Solid.Truck,
		statusNew: false,
	},
	{
		name: "upload",
		outline: Outline.Upload,
		solid: Solid.Upload,
		statusNew: false,
	},
	{
		name: "user",
		outline: Outline.User,
		solid: Solid.User,
		statusNew: false,
	},
	{
		name: "user-add",
		outline: Outline.UserAdd,
		solid: Solid.UserAdd,
		statusNew: false,
	},
	{
		name: "user-circle",
		outline: Outline.UserCircle,
		solid: Solid.UserCircle,
		statusNew: false,
	},
	{
		name: "user-group",
		outline: Outline.UserGroup,
		solid: Solid.UserGroup,
		statusNew: false,
	},
	{
		name: "user-remove",
		outline: Outline.UserRemove,
		solid: Solid.UserRemove,
		statusNew: false,
	},
	{
		name: "users",
		outline: Outline.Users,
		solid: Solid.Users,
		statusNew: false,
	},
	{
		name: "variable",
		outline: Outline.Variable,
		solid: Solid.Variable,
		statusNew: false,
	},
	{
		name: "video-camera",
		outline: Outline.VideoCamera,
		solid: Solid.VideoCamera,
		statusNew: false,
	},
	{
		name: "view-boards",
		outline: Outline.ViewBoards,
		solid: Solid.ViewBoards,
		statusNew: false,
	},
	{
		name: "view-grid",
		outline: Outline.ViewGrid,
		solid: Solid.ViewGrid,
		statusNew: false,
	},
	{
		name: "view-grid-add",
		outline: Outline.ViewGridAdd,
		solid: Solid.ViewGridAdd,
		statusNew: false,
	},
	{
		name: "view-list",
		outline: Outline.ViewList,
		solid: Solid.ViewList,
		statusNew: false,
	},
	{
		name: "volume-off",
		outline: Outline.VolumeOff,
		solid: Solid.VolumeOff,
		statusNew: false,
	},
	{
		name: "volume-up",
		outline: Outline.VolumeUp,
		solid: Solid.VolumeUp,
		statusNew: false,
	},
	{
		name: "wifi",
		outline: Outline.Wifi,
		solid: Solid.Wifi,
		statusNew: false,
	},
	{
		name: "x",
		outline: Outline.X,
		solid: Solid.X,
		statusNew: false,
	},
	{
		name: "x-circle",
		outline: Outline.XCircle,
		solid: Solid.XCircle,
		statusNew: false,
	},
	{
		name: "zoom-in",
		outline: Outline.ZoomIn,
		solid: Solid.ZoomIn,
		statusNew: false,
	},
	{
		name: "zoom-out",
		outline: Outline.ZoomOut,
		solid: Solid.ZoomOut,
		statusNew: false,
	},
]
