import * as Hero from "react-heroicons"

// - "hand"
// - "puzzle"
// - "thumb-down"
// - "thumb-up"
// - "view-grid"
// x "arrows-expand"
// x "fire"
// x "folder-add"
// x "folder-download"
// x "folder-remove"
// x "shopping-bag"
//
// https://github.com/refactoringui/heroicons/issues/55

const originalIcons = [
	{
		tags: [],
		name: "adjustments",
		outline: Hero.AdjustmentsOutlineMd,
		solid: Hero.AdjustmentsSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "annotation",
		outline: Hero.AnnotationOutlineMd,
		solid: Hero.AnnotationSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "archive",
		outline: Hero.ArchiveOutlineMd,
		solid: Hero.ArchiveSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "arrow-circle-down",
		outline: Hero.ArrowCircleDownOutlineMd,
		solid: Hero.ArrowCircleDownSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "arrow-circle-left",
		outline: Hero.ArrowCircleLeftOutlineMd,
		solid: Hero.ArrowCircleLeftSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "arrow-circle-right",
		outline: Hero.ArrowCircleRightOutlineMd,
		solid: Hero.ArrowCircleRightSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "arrow-circle-up",
		outline: Hero.ArrowCircleUpOutlineMd,
		solid: Hero.ArrowCircleUpSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "arrow-down",
		outline: Hero.ArrowDownOutlineMd,
		solid: Hero.ArrowDownSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "arrow-left",
		outline: Hero.ArrowLeftOutlineMd,
		solid: Hero.ArrowLeftSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "arrow-narrow-down",
		outline: Hero.ArrowNarrowDownOutlineMd,
		solid: Hero.ArrowNarrowDownSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "arrow-narrow-left",
		outline: Hero.ArrowNarrowLeftOutlineMd,
		solid: Hero.ArrowNarrowLeftSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "arrow-narrow-right",
		outline: Hero.ArrowNarrowRightOutlineMd,
		solid: Hero.ArrowNarrowRightSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "arrow-narrow-up",
		outline: Hero.ArrowNarrowUpOutlineMd,
		solid: Hero.ArrowNarrowUpSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "arrow-right",
		outline: Hero.ArrowRightOutlineMd,
		solid: Hero.ArrowRightSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "arrow-up",
		outline: Hero.ArrowUpOutlineMd,
		solid: Hero.ArrowUpSolidSm,
		status: false,
	},
	// {
	// 	tags: ["new"],
	// 	name: "arrows-expand",
	// 	outline: Hero.ArrowsExpandOutlineMd,
	// 	solid: Hero.ArrowsExpandSolidSm,
	// 	status: "new",
	// },
	{
		tags: [],
		name: "at-symbol",
		outline: Hero.AtSymbolOutlineMd,
		solid: Hero.AtSymbolSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "badge-check",
		outline: Hero.BadgeCheckOutlineMd,
		solid: Hero.BadgeCheckSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "ban",
		outline: Hero.BanOutlineMd,
		solid: Hero.BanSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "bell",
		outline: Hero.BellOutlineMd,
		solid: Hero.BellSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "book-open",
		outline: Hero.BookOpenOutlineMd,
		solid: Hero.BookOpenSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "bookmark-alt",
		outline: Hero.BookmarkAltOutlineMd,
		solid: Hero.BookmarkAltSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "bookmark",
		outline: Hero.BookmarkOutlineMd,
		solid: Hero.BookmarkSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "briefcase",
		outline: Hero.BriefcaseOutlineMd,
		solid: Hero.BriefcaseSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "calendar",
		outline: Hero.CalendarOutlineMd,
		solid: Hero.CalendarSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "camera",
		outline: Hero.CameraOutlineMd,
		solid: Hero.CameraSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "cash",
		outline: Hero.CashOutlineMd,
		solid: Hero.CashSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "chart-bar",
		outline: Hero.ChartBarOutlineMd,
		solid: Hero.ChartBarSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "chart-pie",
		outline: Hero.ChartPieOutlineMd,
		solid: Hero.ChartPieSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "chart-square-bar",
		outline: Hero.ChartSquareBarOutlineMd,
		solid: Hero.ChartSquareBarSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "chat-alt2",
		outline: Hero.ChatAlt2OutlineMd,
		solid: Hero.ChatAlt2SolidSm,
		status: false,
	},
	{
		tags: [],
		name: "chat-alt",
		outline: Hero.ChatAltOutlineMd,
		solid: Hero.ChatAltSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "chat",
		outline: Hero.ChatOutlineMd,
		solid: Hero.ChatSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "check-circle",
		outline: Hero.CheckCircleOutlineMd,
		solid: Hero.CheckCircleSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "check",
		outline: Hero.CheckOutlineMd,
		solid: Hero.CheckSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "chevron-down",
		outline: Hero.ChevronDownOutlineMd,
		solid: Hero.ChevronDownSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "chevron-left",
		outline: Hero.ChevronLeftOutlineMd,
		solid: Hero.ChevronLeftSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "chevron-right",
		outline: Hero.ChevronRightOutlineMd,
		solid: Hero.ChevronRightSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "chevron-up",
		outline: Hero.ChevronUpOutlineMd,
		solid: Hero.ChevronUpSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "clipboard-check",
		outline: Hero.ClipboardCheckOutlineMd,
		solid: Hero.ClipboardCheckSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "clipboard-copy",
		outline: Hero.ClipboardCopyOutlineMd,
		solid: Hero.ClipboardCopySolidSm,
		status: false,
	},
	{
		tags: [],
		name: "clipboard-list",
		outline: Hero.ClipboardListOutlineMd,
		solid: Hero.ClipboardListSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "clipboard",
		outline: Hero.ClipboardOutlineMd,
		solid: Hero.ClipboardSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "clock",
		outline: Hero.ClockOutlineMd,
		solid: Hero.ClockSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "cloud-download",
		outline: Hero.CloudDownloadOutlineMd,
		solid: Hero.CloudDownloadSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "cloud-upload",
		outline: Hero.CloudUploadOutlineMd,
		solid: Hero.CloudUploadSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "code",
		outline: Hero.CodeOutlineMd,
		solid: Hero.CodeSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "cog",
		outline: Hero.CogOutlineMd,
		solid: Hero.CogSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "collection",
		outline: Hero.CollectionOutlineMd,
		solid: Hero.CollectionSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "color-swatch",
		outline: Hero.ColorSwatchOutlineMd,
		solid: Hero.ColorSwatchSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "credit-card",
		outline: Hero.CreditCardOutlineMd,
		solid: Hero.CreditCardSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "currency-dollar",
		outline: Hero.CurrencyDollarOutlineMd,
		solid: Hero.CurrencyDollarSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "currency-euro",
		outline: Hero.CurrencyEuroOutlineMd,
		solid: Hero.CurrencyEuroSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "currency-pound",
		outline: Hero.CurrencyPoundOutlineMd,
		solid: Hero.CurrencyPoundSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "currency-rupee",
		outline: Hero.CurrencyRupeeOutlineMd,
		solid: Hero.CurrencyRupeeSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "currency-yen",
		outline: Hero.CurrencyYenOutlineMd,
		solid: Hero.CurrencyYenSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "cursor-click",
		outline: Hero.CursorClickOutlineMd,
		solid: Hero.CursorClickSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "desktop-computer",
		outline: Hero.DesktopComputerOutlineMd,
		solid: Hero.DesktopComputerSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "document-add",
		outline: Hero.DocumentAddOutlineMd,
		solid: Hero.DocumentAddSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "document-download",
		outline: Hero.DocumentDownloadOutlineMd,
		solid: Hero.DocumentDownloadSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "document-duplicate",
		outline: Hero.DocumentDuplicateOutlineMd,
		solid: Hero.DocumentDuplicateSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "document-remove",
		outline: Hero.DocumentRemoveOutlineMd,
		solid: Hero.DocumentRemoveSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "document-report",
		outline: Hero.DocumentReportOutlineMd,
		solid: Hero.DocumentReportSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "document",
		outline: Hero.DocumentOutlineMd,
		solid: Hero.DocumentSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "dots-circle-horizontal",
		outline: Hero.DotsCircleHorizontalOutlineMd,
		solid: Hero.DotsCircleHorizontalSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "dots-horizontal",
		outline: Hero.DotsHorizontalOutlineMd,
		solid: Hero.DotsHorizontalSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "dots-vertical",
		outline: Hero.DotsVerticalOutlineMd,
		solid: Hero.DotsVerticalSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "download",
		outline: Hero.DownloadOutlineMd,
		solid: Hero.DownloadSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "duplicate",
		outline: Hero.DuplicateOutlineMd,
		solid: Hero.DuplicateSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "emoji-happy",
		outline: Hero.EmojiHappyOutlineMd,
		solid: Hero.EmojiHappySolidSm,
		status: false,
	},
	{
		tags: [],
		name: "emoji-sad",
		outline: Hero.EmojiSadOutlineMd,
		solid: Hero.EmojiSadSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "exclamation-circle",
		outline: Hero.ExclamationCircleOutlineMd,
		solid: Hero.ExclamationCircleSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "exclamation",
		outline: Hero.ExclamationOutlineMd,
		solid: Hero.ExclamationSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "external-link",
		outline: Hero.ExternalLinkOutlineMd,
		solid: Hero.ExternalLinkSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "eye-off",
		outline: Hero.EyeOffOutlineMd,
		solid: Hero.EyeOffSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "eye",
		outline: Hero.EyeOutlineMd,
		solid: Hero.EyeSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "filter",
		outline: Hero.FilterOutlineMd,
		solid: Hero.FilterSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "flag",
		outline: Hero.FlagOutlineMd,
		solid: Hero.FlagSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "folder",
		outline: Hero.FolderOutlineMd,
		solid: Hero.FolderSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "globe-alt",
		outline: Hero.GlobeAltOutlineMd,
		solid: Hero.GlobeAltSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "globe",
		outline: Hero.GlobeOutlineMd,
		solid: Hero.GlobeSolidSm,
		status: false,
	},
	{
		tags: ["new"],
		name: "hand",
		outline: Hero.HandOutlineMd,
		solid: Hero.HandSolidSm,
		status: "new",
	},
	{
		tags: [],
		name: "hashtag",
		outline: Hero.HashtagOutlineMd,
		solid: Hero.HashtagSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "heart",
		outline: Hero.HeartOutlineMd,
		solid: Hero.HeartSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "home",
		outline: Hero.HomeOutlineMd,
		solid: Hero.HomeSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "inbox-in",
		outline: Hero.InboxInOutlineMd,
		solid: Hero.InboxInSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "inbox",
		outline: Hero.InboxOutlineMd,
		solid: Hero.InboxSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "information-circle",
		outline: Hero.InformationCircleOutlineMd,
		solid: Hero.InformationCircleSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "key",
		outline: Hero.KeyOutlineMd,
		solid: Hero.KeySolidSm,
		status: false,
	},
	{
		tags: [],
		name: "library",
		outline: Hero.LibraryOutlineMd,
		solid: Hero.LibrarySolidSm,
		status: false,
	},
	{
		tags: [],
		name: "light-bulb",
		outline: Hero.LightBulbOutlineMd,
		solid: Hero.LightBulbSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "lightning-bolt",
		outline: Hero.LightningBoltOutlineMd,
		solid: Hero.LightningBoltSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "link",
		outline: Hero.LinkOutlineMd,
		solid: Hero.LinkSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "location-marker",
		outline: Hero.LocationMarkerOutlineMd,
		solid: Hero.LocationMarkerSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "lock-closed",
		outline: Hero.LockClosedOutlineMd,
		solid: Hero.LockClosedSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "lock-open",
		outline: Hero.LockOpenOutlineMd,
		solid: Hero.LockOpenSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "logout",
		outline: Hero.LogoutOutlineMd,
		solid: Hero.LogoutSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "mail-open",
		outline: Hero.MailOpenOutlineMd,
		solid: Hero.MailOpenSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "mail",
		outline: Hero.MailOutlineMd,
		solid: Hero.MailSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "menu-alt1",
		outline: Hero.MenuAlt1OutlineMd,
		solid: Hero.MenuAlt1SolidSm,
		status: false,
	},
	{
		tags: [],
		name: "menu-alt2",
		outline: Hero.MenuAlt2OutlineMd,
		solid: Hero.MenuAlt2SolidSm,
		status: false,
	},
	{
		tags: [],
		name: "menu-alt3",
		outline: Hero.MenuAlt3OutlineMd,
		solid: Hero.MenuAlt3SolidSm,
		status: false,
	},
	{
		tags: [],
		name: "menu-alt4",
		outline: Hero.MenuAlt4OutlineMd,
		solid: Hero.MenuAlt4SolidSm,
		status: false,
	},
	{
		tags: [],
		name: "menu",
		outline: Hero.MenuOutlineMd,
		solid: Hero.MenuSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "microphone",
		outline: Hero.MicrophoneOutlineMd,
		solid: Hero.MicrophoneSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "minus-circle",
		outline: Hero.MinusCircleOutlineMd,
		solid: Hero.MinusCircleSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "moon",
		outline: Hero.MoonOutlineMd,
		solid: Hero.MoonSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "newspaper",
		outline: Hero.NewspaperOutlineMd,
		solid: Hero.NewspaperSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "office-building",
		outline: Hero.OfficeBuildingOutlineMd,
		solid: Hero.OfficeBuildingSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "paper-clip",
		outline: Hero.PaperClipOutlineMd,
		solid: Hero.PaperClipSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "pause",
		outline: Hero.PauseOutlineMd,
		solid: Hero.PauseSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "pencil-alt",
		outline: Hero.PencilAltOutlineMd,
		solid: Hero.PencilAltSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "pencil",
		outline: Hero.PencilOutlineMd,
		solid: Hero.PencilSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "phone-incoming",
		outline: Hero.PhoneIncomingOutlineMd,
		solid: Hero.PhoneIncomingSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "phone-outgoing",
		outline: Hero.PhoneOutgoingOutlineMd,
		solid: Hero.PhoneOutgoingSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "phone",
		outline: Hero.PhoneOutlineMd,
		solid: Hero.PhoneSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "photograph",
		outline: Hero.PhotographOutlineMd,
		solid: Hero.PhotographSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "play",
		outline: Hero.PlayOutlineMd,
		solid: Hero.PlaySolidSm,
		status: false,
	},
	{
		tags: [],
		name: "plus-circle",
		outline: Hero.PlusCircleOutlineMd,
		solid: Hero.PlusCircleSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "plus",
		outline: Hero.PlusOutlineMd,
		solid: Hero.PlusSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "printer",
		outline: Hero.PrinterOutlineMd,
		solid: Hero.PrinterSolidSm,
		status: false,
	},
	{
		tags: ["new"],
		name: "puzzle",
		outline: Hero.PuzzleOutlineMd,
		solid: Hero.PuzzleSolidSm,
		status: "new",
	},
	{
		tags: [],
		name: "q-r-code",
		outline: Hero.QRCodeOutlineMd,
		solid: Hero.QRCodeSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "question-mark-circle",
		outline: Hero.QuestionMarkCircleOutlineMd,
		solid: Hero.QuestionMarkCircleSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "receipt-refund",
		outline: Hero.ReceiptRefundOutlineMd,
		solid: Hero.ReceiptRefundSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "refresh",
		outline: Hero.RefreshOutlineMd,
		solid: Hero.RefreshSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "reply",
		outline: Hero.ReplyOutlineMd,
		solid: Hero.ReplySolidSm,
		status: false,
	},
	{
		tags: [],
		name: "scale",
		outline: Hero.ScaleOutlineMd,
		solid: Hero.ScaleSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "search",
		outline: Hero.SearchOutlineMd,
		solid: Hero.SearchSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "selector",
		outline: Hero.SelectorOutlineMd,
		solid: Hero.SelectorSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "share",
		outline: Hero.ShareOutlineMd,
		solid: Hero.ShareSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "shield-check",
		outline: Hero.ShieldCheckOutlineMd,
		solid: Hero.ShieldCheckSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "shield-exclamation",
		outline: Hero.ShieldExclamationOutlineMd,
		solid: Hero.ShieldExclamationSolidSm,
		status: false,
	},
	// {
	// 	tags: ["new"],
	// 	name: "shopping-bag",
	// 	outline: Hero.ShoppingBagOutlineMd,
	// 	solid: Hero.ShoppingBagSolidSm,
	// 	status: "new",
	// },
	{
		tags: [],
		name: "shopping-cart",
		outline: Hero.ShoppingCartOutlineMd,
		solid: Hero.ShoppingCartSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "sort-ascending",
		outline: Hero.SortAscendingOutlineMd,
		solid: Hero.SortAscendingSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "sort-descending",
		outline: Hero.SortDescendingOutlineMd,
		solid: Hero.SortDescendingSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "sparkles",
		outline: Hero.SparklesOutlineMd,
		solid: Hero.SparklesSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "speakerphone",
		outline: Hero.SpeakerphoneOutlineMd,
		solid: Hero.SpeakerphoneSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "star",
		outline: Hero.StarOutlineMd,
		solid: Hero.StarSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "stop",
		outline: Hero.StopOutlineMd,
		solid: Hero.StopSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "sun",
		outline: Hero.SunOutlineMd,
		solid: Hero.SunSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "support",
		outline: Hero.SupportOutlineMd,
		solid: Hero.SupportSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "switch-horizontal",
		outline: Hero.SwitchHorizontalOutlineMd,
		solid: Hero.SwitchHorizontalSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "switch-vertical",
		outline: Hero.SwitchVerticalOutlineMd,
		solid: Hero.SwitchVerticalSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "tag",
		outline: Hero.TagOutlineMd,
		solid: Hero.TagSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "template",
		outline: Hero.TemplateOutlineMd,
		solid: Hero.TemplateSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "terminal",
		outline: Hero.TerminalOutlineMd,
		solid: Hero.TerminalSolidSm,
		status: false,
	},
	{
		tags: ["new"],
		name: "thumb-down",
		outline: Hero.ThumbDownOutlineMd,
		solid: Hero.ThumbDownSolidSm,
		status: "new",
	},
	{
		tags: ["new"],
		name: "thumb-up",
		outline: Hero.ThumbUpOutlineMd,
		solid: Hero.ThumbUpSolidSm,
		status: "new",
	},
	{
		tags: [],
		name: "ticket",
		outline: Hero.TicketOutlineMd,
		solid: Hero.TicketSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "translate",
		outline: Hero.TranslateOutlineMd,
		solid: Hero.TranslateSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "trash",
		outline: Hero.TrashOutlineMd,
		solid: Hero.TrashSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "trending-down",
		outline: Hero.TrendingDownOutlineMd,
		solid: Hero.TrendingDownSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "trending-up",
		outline: Hero.TrendingUpOutlineMd,
		solid: Hero.TrendingUpSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "upload",
		outline: Hero.UploadOutlineMd,
		solid: Hero.UploadSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "user-add",
		outline: Hero.UserAddOutlineMd,
		solid: Hero.UserAddSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "user-circle",
		outline: Hero.UserCircleOutlineMd,
		solid: Hero.UserCircleSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "user-group",
		outline: Hero.UserGroupOutlineMd,
		solid: Hero.UserGroupSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "user-remove",
		outline: Hero.UserRemoveOutlineMd,
		solid: Hero.UserRemoveSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "user",
		outline: Hero.UserOutlineMd,
		solid: Hero.UserSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "users",
		outline: Hero.UsersOutlineMd,
		solid: Hero.UsersSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "view-boards",
		outline: Hero.ViewBoardsOutlineMd,
		solid: Hero.ViewBoardsSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "view-grid-add",
		outline: Hero.ViewGridAddOutlineMd,
		solid: Hero.ViewGridAddSolidSm,
		status: false,
	},
	{
		tags: ["new"],
		name: "view-grid",
		outline: Hero.ViewGridOutlineMd,
		solid: Hero.ViewGridSolidSm,
		status: "new",
	},
	{
		tags: [],
		name: "view-list",
		outline: Hero.ViewListOutlineMd,
		solid: Hero.ViewListSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "volume-off",
		outline: Hero.VolumeOffOutlineMd,
		solid: Hero.VolumeOffSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "volume-up",
		outline: Hero.VolumeUpOutlineMd,
		solid: Hero.VolumeUpSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "x-circle",
		outline: Hero.XCircleOutlineMd,
		solid: Hero.XCircleSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "x",
		outline: Hero.XOutlineMd,
		solid: Hero.XSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "zoom-in",
		outline: Hero.ZoomInOutlineMd,
		solid: Hero.ZoomInSolidSm,
		status: false,
	},
	{
		tags: [],
		name: "zoom-out",
		outline: Hero.ZoomOutOutlineMd,
		solid: Hero.ZoomOutSolidSm,
		status: false,
	},
]

export default originalIcons
